apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cs-aggregate
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
- apiGroups:
  - configsync.gke.io
  resources:
  - reposync
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
  - patch
- apiGroups:
  - kpt.dev
  resources:
  - resourcegroup
  verbs:
  - get
  - list
  - watch
